spring:
  application:
    name: order
  datasource:
    url: jdbc:h2:mem:db
    driverClassName: org.h2.Driver
    username: sa
    password: password

inventory:
  url: http://localhost:8082
catalog:
  url: http://localhost:8080