spring:
  application:
    name: order

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/pos-order}
    username: ${SPRING_DATASOURCE_USERNAME:pgadmin}
    password: ${SPRING_DATASOURCE_PASSWORD:pgadmin}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

inventory:
  url: http://localhost:8082
catalog:
  url: http://localhost:8080